"""add analysis status for async worker

Revision ID: d87c053c128c
Revises: 1b7bafc3f1c5
Create Date: 2026-08-28 22:17:29.903627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87c053c128c'
down_revision: Union[str, Sequence[str], None] = '1b7bafc3f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: Postgres doesn't
    # auto-create an ENUM type for ADD COLUMN (only for CREATE TABLE), so it
    # has to be created explicitly first. Every existing row went through
    # the old synchronous /analyze flow, so it's genuinely complete already
    # - server_default backfills them, then the model's Python-side default
    # takes over for new rows (pending).
    analysis_status_enum = postgresql.ENUM(
        'pending', 'processing', 'complete', 'failed', name='analysis_status'
    )
    analysis_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'analysis_results',
        sa.Column('status', analysis_status_enum, nullable=False, server_default='complete'),
    )
    op.alter_column('analysis_results', 'status', server_default=None)
    op.add_column('analysis_results', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('analysis_results', 'overall_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analysis_results', 'category_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('analysis_results', 'keyword_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'keyword_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('analysis_results', 'category_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('analysis_results', 'overall_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('analysis_results', 'error_message')
    op.drop_column('analysis_results', 'status')
    # ### end Alembic commands ###
    postgresql.ENUM(name='analysis_status').drop(op.get_bind(), checkfirst=True)
